export const PRESETS = [
  'latest-java',
  'latest-java-top',
  'latest-java_partial-auth',
  'flow-crm-tutorial',
  'react',
  'react-crm-tutorial',
  'react-tutorial',
  'test-hybrid-react',
  'default',
  'latest-java_partial-auth_partial-prerelease',
  'archetype-hotswap',
  'archetype-jetty',
  'archetype-spring',
  'vaadin-quarkus',
  'hilla-react-cli',
  'initializer-vaadin-maven-react',
  'initializer-vaadin-maven-flow',
  'initializer-vaadin-gradle-react',
  'initializer-vaadin-gradle-flow',
  'collaboration',
];

export const DEMOS = [
  'control-center',
  'skeleton-starter-flow',
  'skeleton-starter-flow-spring',
  'skeleton-starter-hilla-react',
  'skeleton-starter-hilla-react-gradle',
  'skeleton-starter-flow-cdi',
  'skeleton-starter-hilla-lit',
  'skeleton-starter-hilla-lit-gradle',
  'skeleton-starter-kotlin-spring',
  'business-app-starter-flow',
  'base-starter-spring-gradle',
  'base-starter-flow-quarkus',
  'base-starter-gradle',
  'flow-crm-tutorial',
  'hilla-crm-tutorial',
  'hilla-quickstart-tutorial',
  'hilla-basics-tutorial',
  'flow-quickstart-tutorial',
  'addon-template',
  'npm-addon-template',
  'client-server-addon-template',
  'spreadsheet-demo',
  'vaadin-form-example',
  'vaadin-rest-example',
  'vaadin-localization-example',
  'vaadin-database-example',
  'layout-examples',
  'flow-spring-examples',
  'vaadin-oauth-example',
  'multi-module-example',
  'bookstore-example',
  'bookstore-example:rtl-demo',
  'bakery-app-starter-flow-spring',
  'k8s-demo-app',
  'mpr-demo',
  'mpr-demo_jdk17',
  'testbench-demo',
  'ce-demo',
  'start',
  'spring-guides/gs-crud-with-vaadin/complete',
  'spring-petclinic/spring-petclinic-vaadin-flow',
  'form-filler-demo',
  'flow-hilla-hybrid-example',
  'designer-tutorial',
  'walking-skeleton:v24.8-hybrid',
  'releases-graph',
  'expo-flow',
];

export const DEFAULT_CONFIG = {
  port: 8080,
  timeout: 300,
  version: 'current',
  cluster: 'pit',
  vendor: 'kind' as const,
  ccVersion: 'current',
  dashboard: 'install' as const,
  verbose: false,
  offline: false,
  interactive: false,
  skipTests: false,
  skipCurrent: false,
  skipDev: false,
  skipProd: false,
  skipPw: false,
  skipClean: false,
  skipHelm: false,
  skipBuild: false,
  keepCc: false,
  keepApps: false,
  proxyCc: false,
  eventsCc: false,
  deleteCluster: false,
  pnpm: false,
  vite: false,
  hub: false,
  commit: false,
  test: false,
  gitSsh: false,
  headless: false,
  headed: false,
  starters: [...PRESETS, ...DEMOS].filter(s => s.length > 3).join(','),
};

export const GITHUB_BASE = 'https://github.com/';

export const APP_CONFIGURATIONS = {
  'archetype-hotswap': {
    needsJBR: true,
  },
  'vaadin-oauth-example': {
    properties: {
      'spring.security.oauth2.client.registration.google.client-id':
        '553339476434-a7kb9vna7limjgucee2n0io775ra5qet.apps.googleusercontent.com',
      'spring.security.oauth2.client.registration.google.client-secret':
        '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',
    },
  },
  'mpr-demo': {
    requiresLicense: '~/vaadin.spreadsheet.developer.license',
  },
  'form-filler-demo': {
    requiresEnv: 'OPENAI_TOKEN',
  },
  'vaadin-quarkus': {
    needsQuarkusFix: true,
  },
  'releases-graph': {
    requiresEnv: 'GHTK',
    propertyMapping: {
      'github.personal.token': 'GHTK',
    },
  },
} as const;
