PRESETS="
latest-java
latest-java_partial-nextprerelease
latest-java-top
latest-javahtml
latest-lit
latest-lit-top
latest-java_partial-auth
latest-lit_partial-auth
flow-crm-tutorial_partial-latest
react-tutorial
default
default_partial-nextprerelease
archetype-hotswap
archetype-jetty
archetype-spring
vaadin-quarkus"
DEMOS="
skeleton-starter-flow
skeleton-starter-flow-spring
skeleton-starter-hilla-lit-gradle
skeleton-starter-hilla-react-gradle
skeleton-starter-flow-cdi
business-app-starter-flow
base-starter-spring-gradle
base-starter-flow-quarkus
base-starter-flow-osgi
base-starter-gradle
flow-crm-tutorial
hilla-crm-tutorial
hilla-quickstart-tutorial
hilla-basics-tutorial
flow-quickstart-tutorial
addon-template
addon-starter-flow
client-server-addon-template
spreadsheet-demo
vaadin-flow-karaf-example
npm-addon-template
vaadin-form-example
vaadin-rest-example
vaadin-localization-example
vaadin-database-example
layout-examples
flow-spring-examples
vaadin-oauth-example
multi-module-example
bookstore-example
bakery-app-starter-flow-spring
k8s-demo-app
"
REPOS="
platform
flow-components
component-starter-flow
starter-wizard"