## LIST of starters or demos used in PiT
##  this is a shared list that could be also used in the gh utilities in this repo

PRESETS="
latest-java
latest-java-top
latest-javahtml
latest-lit
latest-lit-top
latest-java_partial-auth
latest-lit_partial-auth
flow-crm-tutorial
react
react-crm-tutorial
react-tutorial
test-hybrid
test-hybrid-react
default
latest-lit_partial-nextprerelease
latest-lit_partial-prerelease
latest-java_partial-auth_partial-prerelease
archetype-hotswap
archetype-jetty
archetype-spring
vaadin-quarkus
hilla-react-cli
initializer-vaadin-maven-react
initializer-vaadin-maven-flow
initializer-vaadin-gradle-react
initializer-vaadin-gradle-flow
collaboration
"
DEMOS="
control-center
skeleton-starter-flow
skeleton-starter-flow-spring
skeleton-starter-hilla-react
skeleton-starter-hilla-react-gradle
skeleton-starter-flow-cdi
skeleton-starter-hilla-lit
skeleton-starter-hilla-lit-gradle
skeleton-starter-kotlin-spring
business-app-starter-flow
base-starter-spring-gradle
base-starter-flow-quarkus
base-starter-gradle
flow-crm-tutorial
hilla-crm-tutorial
hilla-quickstart-tutorial
hilla-basics-tutorial
flow-quickstart-tutorial
addon-template
npm-addon-template
client-server-addon-template
spreadsheet-demo
vaadin-form-example
vaadin-rest-example
vaadin-localization-example
vaadin-database-example
layout-examples
flow-spring-examples
vaadin-oauth-example
multi-module-example
bookstore-example
bookstore-example:rtl-demo
bakery-app-starter-flow-spring
k8s-demo-app
mpr-demo
mpr-demo_jdk17
testbench-demo
ce-demo
start
spring-guides/gs-crud-with-vaadin/complete
spring-petclinic/spring-petclinic-vaadin-flow
form-filler-demo
flow-hilla-hybrid-example
designer-tutorial"

TODO="
appsec-kit-demo:appsec-kit
kubernetes-kit/kubernetes-kit-demo
observability-kit/observability-kit-demo-hilla
observability-kit/observability-kit-demo
sso-kit/sso-kit-demo
appsec-kit/appsec-kit-demo
vaadin-sso-kit-keycloak-demo
"
# The following are disabled until karaf and osgi are supported in 24.x
# and when we know how to PiT the others
REPOS="
base-starter-flow-osgi
vaadin-flow-karaf-example
platform
flow-components
component-starter-flow
starter-wizard
docs
dsp-demo
"

