name: Create Cluster

on: 
  workflow_dispatch:

# jobs:
#   create-cluster:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Create k8s Kind Cluster
#         uses: helm/kind-action@v1
jobs:
  push_container:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:dind
        options: --privileged --shm-size=2g
        # volumes:
        #   - /var/run/docker.sock:/var/run/docker.sock:ro
    container:
      image: ubuntu:latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: '20.9.0'      
      # - name: Install Docker
      #   run: |
      #     apt-get update
      #     apt-get install -y docker.io          
      # - name: Test Docker
      #   run: |
      #     docker version
      #     docker info     
      # - name: Create k8s Kind Cluster
      #   uses: helm/kind-action@v1           
      # - name: Load images
      #   run: |
      #      echo "Sleeping for 100000 seconds"
      #      sleep 1000000        